runtime: java11
env: flex
instance_class: F2
handlers:
  - url: .*
    script: auto
env_variables:
  SPRING_PROFILES_ACTIVE: PROD
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
